module.exports = [
  {
    id: 'p1',
    title: 'Gradient Graphic T-shirt',
    description: 'Vibrant gradient graphic on premium cotton.',
    price: 145,
    rating: 3.5,
    category: 'T-shirts',
    style: 'Casual',
    colors: ['white', 'blue', 'green'],
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p2',
    title: 'Polo with Tipping Details',
    description: 'Classic polo with refined tipping details.',
    price: 180,
    rating: 4.5,
    category: 'Shirts',
    style: 'Formal',
    colors: ['red', 'blue', 'navy'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p3',
    title: 'Black Striped T-shirt',
    description: 'Minimal black striped tee.',
    price: 120,
    rating: 5.0,
    category: 'T-shirts',
    style: 'Casual',
    colors: ['black', 'white'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p4',
    title: 'Skinny Fit Jeans',
    description: 'Stretchy and comfortable skinny fit jeans.',
    price: 240,
    rating: 3.5,
    category: 'Jeans',
    style: 'Casual',
    colors: ['blue', 'navy'],
    sizes: ['Medium', 'Large', 'X-Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p5',
    title: 'Checkered Shirt',
    description: 'Bold checkered flannel shirt.',
    price: 180,
    rating: 4.5,
    category: 'Shirts',
    style: 'Casual',
    colors: ['red', 'black'],
    sizes: ['Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p6',
    title: 'Sleeve Striped T-shirt',
    description: 'Sporty sleeve striped t-shirt.',
    price: 130,
    rating: 4.5,
    category: 'T-shirts',
    style: 'Gym',
    colors: ['orange', 'black'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p7',
    title: 'Vertical Striped Shirt',
    description: 'Vertical stripes for elongating silhouette.',
    price: 212,
    rating: 5.0,
    category: 'Shirts',
    style: 'Formal',
    colors: ['green', 'white'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p8',
    title: 'Courage Graphic T-shirt',
    description: 'Graphic tee with bold courage print.',
    price: 145,
    rating: 4.0,
    category: 'T-shirts',
    style: 'Party',
    colors: ['orange', 'black'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p9',
    title: 'Loose Fit Bermuda Shorts',
    description: 'Lightweight shorts perfect for summer.',
    price: 80,
    rating: 3.0,
    category: 'Shorts',
    style: 'Casual',
    colors: ['blue'],
    sizes: ['Small', 'Medium', 'Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  },
  {
    id: 'p10',
    title: 'One Life Graphic T-shirt',
    description: 'Premium tee with "One Life" graphic.',
    price: 260,
    rating: 4.5,
    category: 'T-shirts',
    style: 'Casual',
    colors: ['green', 'olive', 'navy'],
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    image: '/assets/placeholder.svg',
    thumbnails: ['/assets/placeholder.svg']
  }
];


